### ISSUE TITLE
import scipy.linalg crash

### ISSUE THREAD

**Issue by rloewe** [bh107/bohrium#155]
If you create a python program with only this line:
`import scipy.linalg`
and run it with `-m bohrium`, then it crashes with this error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/rlj/.local/lib/python2.7/site-packages/bohrium/__main__.py", line 35, in <module>
    execfile_wrapper(sys.argv[0])
  File "/Users/rlj/.local/lib/python2.7/site-packages/bohrium/__main__.py", line 20, in execfile_wrapper
    return execfile(path, {"__name__": "__main__", "__file__": path})
  File "linalg.py", line 1, in <module>
    import scipy.linalg
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/__init__.py", line 175, in <module>
    from .basic import *
  File "/usr/local/lib/python2.7/site-packages/scipy/linalg/basic.py", line 21, in <module>
    from ._solve_toeplitz import levinson
  File "__init__.pxd", line 861, in init scipy.linalg._solve_toeplitz (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-8Za6y9-build/scipy/linalg/_solve_toeplitz.c:19966)
TypeError: numpy.ufunc is not a type object
```

**Comment by dionhaefner** [comment]
On the current master it fails with

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/bohrium/__main__.py", line 35, in <module>
    execfile_wrapper(sys.argv[0])
  File "/usr/lib/python2.7/dist-packages/bohrium/__main__.py", line 20, in execfile_wrapper
    return execfile(path, {"__name__": "__main__", "__file__": path})
  File "test.py", line 1, in <module>
    from scipy import linalg
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/__init__.py", line 69, in <module>
    from numpy import *
AttributeError: 'module' object has no attribute 'aliases'
```

**Comment by madsbk** [comment]
import of scipy should work in master now
