### ISSUE TITLE
netCDF4 import fails

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#218]
```python
from netCDF4 import Dataset
```

yields:

```
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/netcdftime/__init__.py:1: UserWarning: Bohrium does not support the dtype 'object', the new array will be a regular NumPy array.
  from ._netcdftime import utime, JulianDayFromDate, DateFromJulianDay
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/netcdftime/__init__.py:1: RuntimeWarning: Bohrium does not support indexing with arrays. Bohrium will return a NumPy copy of the indexed array.
  from ._netcdftime import utime, JulianDayFromDate, DateFromJulianDay
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/netcdftime/__init__.py:1: RuntimeWarning: Bohrium does not support indexing with arrays. It will be handled by the original NumPy.
  from ._netcdftime import utime, JulianDayFromDate, DateFromJulianDay
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/netcdftime/__init__.py:1: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  from ._netcdftime import utime, JulianDayFromDate, DateFromJulianDay
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/numpy/core/_methods.py:38: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  return umr_any(a, axis, dtype, out, keepdims)
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/bohrium/masking.py:88: UserWarning: Bohrium only supports where() when 'x' and 'y' are specified
  warnings.warn("Bohrium only supports where() when 'x' and 'y' are specified")
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/bohrium/masking.py:89: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  return numpy.where(condition, x, y)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/bohrium/__main__.py", line 37, in <module>
    execfile_wrapper(sys.argv[0])
  File "/usr/lib/python2.7/dist-packages/bohrium/__main__.py", line 20, in execfile_wrapper
    return execfile(path, {"__name__": "__main__", "__file__": path})
  File "netcdf_test.py", line 1, in <module>
    from netCDF4 import Dataset
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
  File "netCDF4/_netCDF4.pyx", line 943, in init netCDF4._netCDF4 (netCDF4/_netCDF4.c:83340)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/netcdftime/__init__.py", line 1, in <module>
    from ._netcdftime import utime, JulianDayFromDate, DateFromJulianDay
  File "netcdftime/_netcdftime.pyx", line 1186, in init netcdftime._netcdftime (netcdftime/_netcdftime.c:30930)
  File "netcdftime/_netcdftime.pyx", line 732, in netcdftime._netcdftime.utime.__init__ (netcdftime/_netcdftime.c:13224)
  File "netcdftime/_netcdftime.pyx", line 127, in netcdftime._netcdftime.JulianDayFromDate (netcdftime/_netcdftime.c:3397)
AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by dionhaefner** [comment]
Funnily enough,  this seems to be fixed along with #223
