### ISSUE TITLE
Python 3 Corruption

### ISSUE THREAD

**Issue by madsbk** [bh107/bohrium#281]
When converting a Bohrium into a NumPy array corrupts the objects in Python 3:
```python
import numpy as np
import bohrium as bh
a = bh.arange(10)
b = np.array(a)
```
Results in (or something similar):
```
RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  b = np.array(a)
python3: Modules/gcmodule.c:345: update_refs: Assertion `_PyGCHead_REFS(gc) == GC_REACHABLE' failed.
Aborted
```

**Comment by dionhaefner** [comment]
I am currently running into this issue. When running my code with Python 3, it most of the time just segfaults. However, sometimes, I am getting strange errors like that:

```
Exception ignored in: <bound method Base.__del__ of <bohrium.target.target_bhc.Base object at 0x7f7e484c2550>>
Traceback (most recent call last):
  File "/home/dion/.virtualenvs/bohrium3/lib/python3.5/site-packages/bohrium/target/target_bhc.py", line 60, in __del__
    eval("bhc_destroy_A%s(self.bhc_obj)" % self.dtype_name)
SyntaxError: ('invalid syntax', ('<string>', 1, 25, 'bhc_destroy_Auint64(self.bhc_obj)'))
```

```
Exception ignored in: <bound method View.__del__ of <bohrium.target.target_bhc.View object at 0x7f7e2dee7a90>>
Traceback (most recent call last):
  File "/home/dion/.virtualenvs/bohrium3/lib/python3.5/site-packages/bohrium/target/target_bhc.py", line 81, in __del__
    eval("bhc_destroy_A%s(self.bhc_obj)" % self.dtype_name)
SyntaxError: ('invalid syntax', ('<string>', 1, 24, 'bhc_destroy_Aint64(self.bhc_obj)'))
```

```
Traceback (most recent call last):
  File "bhary.pyx", line 301, in bhary.get_bhc_data_pointer (/home/dion/software/bohrium/build/bridge/npbackend/bhary.c:7039)
  File "/home/dion/.virtualenvs/bohrium3/lib/python3.5/site-packages/bohrium/target/target_bhc.py", line 120, in get_data_pointer
    exec("bhc_sync_A%s(ary)" % dtype)
  File "<string>", line 1, in <module>
TypeError: bhc_sync_Abool8() takes exactly 1 argument (0 given)
```

and finally

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "solve_stream_test.py", line 77, in <module>
    passed = StreamfunctionTest().run()
  File "/home/dion/codes/veros/test/tests/test_base.py", line 168, in run
    self.initialize()
  File "solve_stream_test.py", line 55, in initialize
    init_new(self.veros_new)
  File "/home/dion/codes/veros/veros/decorators.py", line 50, in veros_method_wrapper
    res = function(*args, **kwargs)
  File "/home/dion/codes/veros/veros/core/external/streamfunction_init.py", line 40, in streamfunction_init
    veros.boundary_mask = veros.boundary_mask.copy2numpy()
  File "bhary.pyx", line 98, in bhary.fix_biclass_wrapper.inner (/home/dion/software/bohrium/build/bridge/npbackend/bhary.c:2805)
  File "/home/dion/.virtualenvs/bohrium3/lib/python3.5/site-packages/bohrium/ufuncs.py", line 107, in assign
    get_base(ary)._data_bhc2np()
SystemError: <built-in function del_bhc> returned a result with an error set
```

I was really surprised by all the "invalid syntax" errors created by the "exec" calls, and thought it might be helpful.

**Comment by dionhaefner** [comment]
https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst

Is there a status on this? Our tests are still failing on Python 3 😢

**Comment by omegahm** [comment]
@dionhaefner Do you have any more specific examples of what are not working for you? We run all of our own tests with both 2.7 and 3.5 and they are green all the way.

**Comment by dionhaefner** [comment]
The problem is hard to isolate, and it does not occur deterministically. One thing I was able to reproduce consistently is a segfault *after* running the following snippet:

```python
import bohrium as np
from scipy.sparse import dia_matrix
from scipy.sparse.linalg import bicgstab
from scipy.sparse import identity

n = 10**5
diagonals = np.ones((5,n)) * -1
diagonals[2] = 4.0
offsets = (-100, -1, 0, 1, 100)
matrix = dia_matrix((diagonals, offsets), shape=(n, n))
rhs = np.ones(n)

x0 = np.random.rand(n)

solution, info = bicgstab(matrix, rhs, x0=x0, tol=1e-06, maxiter= 10000)
```

Output:

```
/home/dion/.virtualenvs/veros3/lib/python3.6/site-packages/scipy/sparse/linalg/isolve/utils.py:98: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  x = array(x0, dtype=xtype)
/home/dion/.virtualenvs/veros3/lib/python3.6/site-packages/scipy/sparse/linalg/isolve/iterative.py:167: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  revcom(b, x, work, iter_, resid, info, ndx1, ndx2, ijob)
/home/dion/.virtualenvs/veros3/lib/python3.6/site-packages/scipy/sparse/dia.py:239: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  dia_matvec(M,N, len(self.offsets), L, self.offsets, self.data, x.ravel(), y.ravel())
Segmentation fault (core dumped)
```

This segfault does not occur on Python 2.7. The real code in question also calls this SciPy solver, and segfaults occur at random either while or after running. While it does help in the code above to copy all arrays to NumPy, this does not work in the real code that is more complicated.

**Comment by dionhaefner** [comment]
I found a workaround. The issue was that I created an array in the following way:

```python
a = (bh.random.rand(100), bh.random.rand(100))
b = bh.array(a)
```

This leads to a segmentation fault, too.

**Comment by dionhaefner** [comment]
Update: The example from my last post works now, but the original

```python
import numpy as np
import bohrium as bh
a = bh.arange(10)
b = np.array(a)
```

still segfaults on exit.
