### ISSUE TITLE
scipy.io import fails

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#283]
```python
import scipy.io
```

gives 

```
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/bohrium/array_create.py:306: UserWarning: Bohrium does not support the dtype '[('mdtype', '<u4'), ('byte_count', '<u4')]', the new array will be a regular NumPy array.
  A = empty(shape, dtype=dtype, bohrium=bohrium)
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dion/.local/lib/python2.7/site-packages/bohrium/__main__.py", line 31, in <module>
    execfile_wrapper(sys.argv[0])
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/bohrium/__init__.py", line 46, in wrapper
    result = function(*args, **kwargs)
  File "/home/dion/.local/lib/python2.7/site-packages/bohrium/__main__.py", line 20, in execfile_wrapper
    return execfile(path, {"__name__": "__main__", "__file__": path})
  File "bh_test.py", line 1, in <module>
    import scipy.io
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/io/__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 14, in <module>
    from .mio5 import MatFile5Reader, MatFile5Writer
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 462, in <module>
    class VarWriter5(object):
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/io/matlab/mio5.py", line 464, in VarWriter5
    mat_tag = np.zeros((), NDT_TAG_FULL)
  File "bhary.pyx", line 98, in bhary.fix_biclass_wrapper.inner (/home/dion/software/bohrium/build/bridge/npbackend/bhary.c:2460)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/bohrium/array_create.py", line 307, in zeros
    A[...] = A.dtype.type(0)
TypeError: Empty data-type
```

**Comment by omegahm** [comment]
I get a different error, when trying to do the same

```
    A[...] = A.dtype.type(0)
ValueError: setting an array element with a sequence.
```

I've just created a `scipy-io.py` file with nothing but `import scipy.io` and then run `python -m bohrium scipy-io.py`.

**Comment by dionhaefner** [comment]
Works for me now (on master).

**Comment by madsbk** [comment]
On master we are testing `import scipy.io; res = M.ones(10)` and it works both on Linux and OSX
