### ISSUE TITLE
import scipy.io fails with SciPy 0.19.0

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#319]
Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dion/.local/lib/python2.7/site-packages/bohrium/__main__.py", line 31, in <module>
    execfile_wrapper(sys.argv[0])
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/bohrium/__init__.py", line 58, in wrapper
    result = function(*args, **kwargs)
  File "/home/dion/.local/lib/python2.7/site-packages/bohrium/__main__.py", line 20, in execfile_wrapper
    return execfile(path, {"__name__": "__main__", "__file__": path})
  File "test.py", line 1, in <module>
    import scipy.io
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/io/__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 12, in <module>
    from .miobase import get_matfile_version, docfiller
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/io/matlab/miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/misc/__init__.py", line 53, in <module>
    from scipy.interpolate._pade import pade
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/interpolate/__init__.py", line 176, in <module>
    from .interpolate import *
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/interpolate/interpolate.py", line 32, in <module>
    from .interpnd import _ndim_coords_from_arrays
  File "scipy/interpolate/interpnd.pyx", line 1, in init scipy.interpolate.interpnd (scipy/interpolate/interpnd.c:25999)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/spatial/__init__.py", line 96, in <module>
    from ._spherical_voronoi import SphericalVoronoi
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py", line 15, in <module>
    import numpy.matlib
ImportError: No module named matlib
```

**Comment by dionhaefner** [comment]
The same happens with

```python
import scipy.interpolate
```

when NumPy 1.12.1 is installed (regardless whether SciPy 0.19 or 0.18.x is used).
