### ISSUE TITLE
Add numpy version information

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#377]
We ran into the problem that installing Bohrium via ``conda`` lead to a version conflict:

```
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "random123.pyx", line 557, in random123.RandomState.randn (/tmp/conda_build_tmp/bohrium_1497319250546/work/build/bridge/npbackend/random123.c:4965)
  File "random123.pyx", line 692, in random123.RandomState.standard_normal (/tmp/conda_build_tmp/bohrium_1497319250546/work/build/bridge/npbackend/random123.c:6091)
  File "random123.pyx", line 260, in random123.RandomState.random_sample (/tmp/conda_build_tmp/bohrium_1497319250546/work/build/bridge/npbackend/random123.c:3232)
  File "random123.pyx", line 214, in random123.RandomState.random123 (/tmp/conda_build_tmp/bohrium_1497319250546/work/build/bridge/npbackend/random123.c:2895)
  File "bhary.pyx", line 120, in bhary.new (/tmp/conda_build_tmp/bohrium_1497319250546/work/build/bridge/npbackend/bhary.c:3752)
ImportError: numpy.core.multiarray failed to import
```

So we now face the task to find out which version of NumPy Bohrium was compiled with. Would it be possible to add that information as a variable in the Python interface? So you could do e.g.

```python
import bohrium as bh
bh.info()
```

to get some information about how Bohrium was built.

**Comment by madsbk** [comment]
Get the version with:
```python
import bohrium as bh
print bh.bh_info.numpy_version()
```
