### ISSUE TITLE
Bohrium gives wrong result when making an array of singleton arrays.

### ISSUE THREAD

**Issue by Ektorus** [bh107/bohrium#40]
The following code gives the correct result in numpy, but not in Bohrium (cfcd17f77716c8c2b4bee09a782bced5dfba59a5):

``` python
import numpy as np
a = map(np.array, range(10))
print np.array(a)
print

import bohrium as bh
a = map(bh.array, range(10))
print bh.array(a)
print
```

This will give the following result (or something similar):

``` python
[0 1 2 3 4 5 6 7 8 9]

[139745276506112 139745276469248 139745276461056 139745276452864
 139745276444672 139745276436480 139745276428288 139745276420096
 139745276411904 139745276403712]
```

**Comment by omegahm** [comment]
This gives a `ValueError` now. Should still be fixed.

```
Traceback (most recent call last):
  File "40.py", line 8, in <module>
    print bh.array(a)
  File "bhary.pyx", line 74, in bhary.fix_returned_biclass.inner (/tmp/bhbuild_cpu/bridge/npbackend/bhary.c:1676)
  File "/Users/ohm/.local/lib/python2.7/site-packages/bohrium/array_create.py", line 123, in array
    subok=subok, ndmin=ndmin)
  File "bhary.pyx", line 74, in bhary.fix_returned_biclass.inner (/tmp/bhbuild_cpu/bridge/npbackend/bhary.c:1676)
ValueError: setting an array element with a sequence.
```
