### ISSUE TITLE
sqrt report ValueError on any input

### ISSUE THREAD

**Issue by Baekalfen** [bh107/bohrium#414]
Any value given to Bohrium's sqrt function reports a broadcasting error:

    >>> bohrium.sqrt(1)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "bhary.pyx", line 104, in bhary.fix_biclass_wrapper.inner
      File "ufuncs.pyx", line 154, in ufuncs.Ufunc.__call__
      File "bhary.pyx", line 104, in bhary.fix_biclass_wrapper.inner
      File "/usr/local/lib/python2.7/site-packages/bohrium/array_manipulation.py", line 466, in broadcast_arrays
        bcast = numpy.broadcast(*args)
    ValueError: Need at least two and fewer than (32) array objects.
    >>> bohrium.sqrt(bohrium.arange(10))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "bhary.pyx", line 104, in bhary.fix_biclass_wrapper.inner
      File "ufuncs.pyx", line 154, in ufuncs.Ufunc.__call__
      File "bhary.pyx", line 104, in bhary.fix_biclass_wrapper.inner
      File "/usr/local/lib/python2.7/site-packages/bohrium/array_manipulation.py", line 466, in broadcast_arrays
        bcast = numpy.broadcast(*args)
    ValueError: Need at least two and fewer than (32) array objects.

The same calls to NumPy works as expected:

    >>> numpy.sqrt(1)
    1.0
    >>> numpy.sqrt(np.arange(10))
    array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
            2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

**Comment by omegahm** [comment]
Are you using `master`? Or have you installed Bohrium from one of the sources?

I have just recompiled `master` and get:

```python
>>> bh.sqrt(1)
1.0
```

however, in the second case I get:

```python
>>> bh.sqrt(bh.arange(10))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bhary.pyx", line 104, in bhary.fix_biclass_wrapper.inner
  File "ufuncs.pyx", line 192, in ufuncs.Ufunc.__call__
  File "_util.pyx", line 95, in _util.type_sig
TypeError: The ufunc bohrium.sqrt() does not support input data type: int64.
```

This can be forced to float with:

```python
>>> bh.sqrt(bh.arange(10).astype(bh.float))
array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])
```

which is the same result as NumPy.

---

I'll look into automatically casting to float, if `sqrt` is used on integer arrays.

**Comment by Baekalfen** [comment]
To verify, I uninstalled Bohrium, checked I couldn't import it in Python and reinstalled. The issue is still present.

I installed through Brew on macOS, using `brew install bohrium —HEAD`:

    ❯ brew install bohrium --HEAD
    Updating Homebrew...
    ==> Auto-updated Homebrew!
    [Redacted some output about updated packages in Brew]
    ==> Installing bohrium from bh107/bohrium
    ==> Cloning https://github.com/bh107/bohrium.git
    Updating /Users/mads/Library/Caches/Homebrew/bohrium--git
    ==> Checking out branch master
    ==> cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/bohrium/HEAD-a945681 -Wno-dev -DUSE_WERROR=ON -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -
    ==> make
    ==> make install
    🍺  /usr/local/Cellar/bohrium/HEAD-a945681: 282 files, 18.7MB, built in 3 minutes 6 seconds

**Comment by Baekalfen** [comment]
I think we found the culprit! Bohrium reported `1.10.1`. Updating to NumPy 1.13.1 fixes the issue of broadcasting, and presents the same result as you.

    >>> import bohrium
    >>> bohrium.__version__
    '1.13.1'
    >>> bohrium.sqrt(1)
    1.0
    >>> bohrium.sqrt(bohrium.arange(12))
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "bhary.pyx", line 104, in bhary.fix_biclass_wrapper.inner
      File "ufuncs.pyx", line 192, in ufuncs.Ufunc.__call__
      File "_util.pyx", line 95, in _util.type_sig
    TypeError: The ufunc bohrium.sqrt() does not support input data type: int64.
    >>> bohrium.sqrt(bohrium.arange(12).astype(float))
    array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
            2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
            3.16227766,  3.31662479])

Unless you want to dig further into the root cause, I think we can close the issue :)

**Comment by omegahm** [comment]
@madsbk We don't support NumPy `1.10.1`? We should probably write that down somewhere. 😏

I'll close this issue for now.
