### ISSUE TITLE
Error when running bh-info

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#437]
`bh-info` crashes with

```
bh-info - Printing formation of the current Bohrium setup
Found config file:
	/home/dion/.bohrium/config.ini
Component stack: 
	default = bcexp_cpu, bccon, node, openmp
JIT compiler options:
	openmp.compiler_cmd = "/usr/bin/cc -x c -fPIC -shared  -std=gnu99  -O3 -march=native -Werror -fopenmp -fopenmp-simd -I/home/dion/.local/share/bohrium/include -lm -L/home/dion/.local/lib -lbh {IN} -o {OUT}"
Fail cmd ""/usr/bin/cc -x c -fPIC -shared  -std=gnu99  -O3 -march=native -Werror -fopenmp -fopenmp-simd -I/home/dion/.local/share/bohrium/include -lm -L/home/dion/.local/lib -lbh {IN} -o {OUT}" -v"
Traceback (most recent call last):
  File "/home/dion/.local/bin/bh-info", line 114, in <module>
    print_compiler(args.config, args.stack[-1])
  File "/home/dion/.local/bin/bh-info", line 92, in print_compiler
    version = subprocess.check_output(cmd_version, stderr=subprocess.STDOUT, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '"/usr/bin/cc -x c -fPIC -shared  -std=gnu99  -O3 -march=native -Werror -fopenmp -fopenmp-simd -I/home/dion/.local/share/bohrium/include -lm -L/home/dion/.local/lib -lbh {IN} -o {OUT}" -v' returned non-zero exit status 127
```

Seems like the `{IN}` and `{OUT}` placeholders don't get replaced.

**Comment by madsbk** [comment]
`bh-info` has been removed in 7d73e9be6ec5c15034969444153d7e033bb7f236
