### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by madsthoudahl** [bh107/bohrium#46]
the line of code:
    test = numpy.array(result)
where result is a bohrium array of shape (30,30), generates the following error:

Traceback (most recent call last):
  File "ndarray.pyx", line 239, in ndarray.get_bhc_data_pointer (/home/koeus/hpc/bohrium/build/bridge/npbackend/ndarray.c:4065)
  File "ndarray.pyx", line 171, in ndarray.get_bhc (/home/koeus/hpc/bohrium/build/bridge/npbackend/ndarray.c:2986)
RuntimeWarning: tp_compare didn't return -1 or -2 for exception
Segmentation fault (core dumped)

**Comment by madsthoudahl** [comment]
the bh107/xraysim branch bohrium_issue46 has the full sourcecode

**Comment by madsbk** [comment]
I cannot reproduces it.
Is this still an issue as of 9194f8372b07d8febba696b741fc0b71b274f0b7 ?

**Comment by madsbk** [comment]
Bohrium now supports xraysim fully.
