### ISSUE TITLE
Cannot plot Bohrium arrays with Matplotlib anymore

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#476]
Since `__array_ufunc__` was implemented, I sometimes get crashes like the following on Numpy 1.13.3:

```python
import bohrium as bh
import matplotlib.pyplot as plt

a = bh.random.randn(100, 100)
plt.imshow(a)
plt.show()
```

crashes with

```
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/cbook/__init__.py:1350: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  x = np.array(x, subok=True, copy=copy)
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py:380: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  A_scaled[:] = A
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py:381: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  A_scaled -= a_min
/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py:382: RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy.
  if a_min != a_max:
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1544, in __call__
    return self.func(*args)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 595, in callit
    func(*args)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 323, in idle_draw
    self.draw()
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py", line 548, in draw
    renderer, renderer.get_image_magnification())
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py", line 774, in make_image
    unsampled=unsampled)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py", line 383, in _make_image
    A_scaled /= ((a_max - a_min) / 0.8)
  File "ufuncs.pyx", line 594, in ufuncs._handle__array_ufunc__ (/home/dion/software/bohrium/build/bridge/npbackend/ufuncs.c:12150)
  File "bhary.pyx", line 105, in bhary.fix_biclass_wrapper.inner (/home/dion/software/bohrium/build/bridge/npbackend/bhary.c:3381)
  File "ufuncs.pyx", line 543, in ufuncs.TrueDivide.__call__ (/home/dion/software/bohrium/build/bridge/npbackend/ufuncs.c:11521)
TypeError: 'tuple' object does not support item assignment
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1544, in __call__
    return self.func(*args)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 233, in resize
    self.show()
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 304, in draw
    FigureCanvasAgg.draw(self)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py", line 548, in draw
    renderer, renderer.get_image_magnification())
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py", line 774, in make_image
    unsampled=unsampled)
  File "/home/dion/.virtualenvs/bohrium/local/lib/python2.7/site-packages/matplotlib/image.py", line 383, in _make_image
    A_scaled /= ((a_max - a_min) / 0.8)
  File "ufuncs.pyx", line 594, in ufuncs._handle__array_ufunc__ (/home/dion/software/bohrium/build/bridge/npbackend/ufuncs.c:12150)
  File "bhary.pyx", line 105, in bhary.fix_biclass_wrapper.inner (/home/dion/software/bohrium/build/bridge/npbackend/bhary.c:3381)
  File "ufuncs.pyx", line 543, in ufuncs.TrueDivide.__call__ (/home/dion/software/bohrium/build/bridge/npbackend/ufuncs.c:11521)
TypeError: 'tuple' object does not support item assignment

```

**Comment by omegahm** [comment]
Which version of `matplotlib` are you using?

I get 

```python
>>> import matplotlib
>>> matplotlib.__version__
'1.5.1'
```

and here it works fine.

**Comment by omegahm** [comment]
I do get same error when I updated `matplotlib` to `2.1.0`.

**Comment by dionhaefner** [comment]
2.1.0 (most recent I guess). Can confirm that 1.5.1 works.

**Comment by madsbk** [comment]
This reproduces the problem:
```python
import numpy as np
import bohrium as bh
A = np.array(44)
A /= bh.array(42)
```
