### ISSUE TITLE
Homebrew gives a 'deprecated' warning

### ISSUE THREAD

**Issue by Baekalfen** [bh107/bohrium#502]
Homebrew gives the following warning, when calling `brew update`:

```
Warning: Calling 'depends_on :python' is deprecated!
Use 'depends_on "python"' instead.
/usr/local/Homebrew/Library/Taps/bh107/homebrew-bohrium/Formula/bohrium.rb:14:in `<class:Bohrium>'
Please report this to the bh107/bohrium tap!

Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Taps/bh107/homebrew-bohrium/Formula/bohrium.rb:15:in `<class:Bohrium>'
Please report this to the bh107/bohrium tap!
```

**Comment by omegahm** [comment]
Fixed with https://github.com/bh107/homebrew-bohrium/commit/d8ff014726f536648640f0be64c4061cf9c86e7e. (Still running on Jenkins)

**Comment by omegahm** [comment]
Should have been fixed with the above mentioned commit.
