### ISSUE TITLE
Broken "bhary.so" library on macOs.

### ISSUE THREAD

**Issue by KelSolaar** [bh107/bohrium#520]
Hi,

The "bhary.so" library is seemingly broken on macOs:

``` bash
(colour-2.7) Kali:Environments kelsolaar$ python
Python 2.7.14 (default, Mar 10 2018, 00:01:04)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bohrium
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kelsolaar/Documents/Development/Environments/colour-2.7/lib/python2.7/site-packages/bohrium/__init__.py", line 21, in <module>
    from .array_create import *
  File "/Users/kelsolaar/Documents/Development/Environments/colour-2.7/lib/python2.7/site-packages/bohrium/array_create.py", line 7, in <module>
    from . import bhary
ImportError: dlopen(/Users/kelsolaar/Documents/Development/Environments/colour-2.7/lib/python2.7/site-packages/bohrium/bhary.so, 2): no suitable image found.  Did find:
	/Users/kelsolaar/Documents/Development/Environments/colour-2.7/lib/python2.7/site-packages/bohrium/bhary.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/kelsolaar/Documents/Development/Environments/colour-2.7/lib/python2.7/site-packages/bohrium/bhary.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

Using *otool*:

```
(colour-2.7) Kali:Environments kelsolaar$ otool -hv /Users/kelsolaar/Documents/Development/Environments/colour-2.7/lib/python2.7/site-packages/bohrium/bhary.so
llvm-objdump: '/Users/kelsolaar/Documents/Development/Environments/colour-2.7/lib/python2.7/site-packages/bohrium/bhary.so': Object is not a Mach-O file type.
```

And a working library for reference:

```
(colour-2.7) Kali:Environments kelsolaar$ otool -hv /usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages/OpenImageIO.so
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
MH_MAGIC_64  X86_64        ALL  0x00      BUNDLE    41       3704   NOUNDEFS DYLDLINK TWOLEVEL WEAK_DEFINES BINDS_TO_WEAK
```

**Comment by KelSolaar** [comment]
Hi @madsbk,

Confirming that 0.9.0 now import correctly:

```
(colour-2.7) Kali:colour kelsolaar$ pip install bohrium
Collecting bohrium
  Downloading bohrium-0.9.0.post0-cp27-cp27m-macosx_10_12_x86_64.whl (3.2MB)
    100% |████████████████████████████████| 3.2MB 196kB/s
Collecting gcc7 (from bohrium)
  Downloading gcc7-0.0.4-py2.py3-none-macosx_10_12_x86_64.whl (32.8MB)
    100% |████████████████████████████████| 32.8MB 18kB/s
Requirement already satisfied: numpy>=1.13 in /usr/local/anaconda3/envs/colour-2.7/lib/python2.7/site-packages (from bohrium)
Installing collected packages: gcc7, bohrium
Successfully installed bohrium-0.9.0.post0 gcc7-0.0.4
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(colour-2.7) Kali:colour kelsolaar$ python
Python 2.7.14 | packaged by conda-forge | (default, Dec 25 2017, 01:18:54)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bohrium as np
>>> np.random.random(3)
array([0.26794474, 0.02373637, 0.52490062])
```

Cheers,

Thomas

**Comment by madsbk** [comment]
Great, glad to hear!
