### ISSUE TITLE
np.linalg.norm doesn't work, when performed along an axis

### ISSUE THREAD

**Issue by Baekalfen** [bh107/bohrium#588]
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
    [GCC 7.3.0] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import bohrium as np
    >>> np.linalg.norm(np.ones((2,2,2)),axis=0)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "bohrium/bhary.pyx", line 95, in bohrium.bhary.fix_biclass_wrapper.inner
      File "/home/mads/.bin/bohrium/lib/python2.7/site-packages/bohrium/linalg.py", line 291, in norm
        raise NotImplementedError("Unsupported value of param ord=%s" % axis)
    NotImplementedError: Unsupported value of param ord=0

Calling it without an axis works, but gives of course a different result:

    >>> np.linalg.norm(np.ones((2,2,2)))
    2.82843

**Comment by dionhaefner** [comment]
In case it's not already obvious, a workaround is

```python
np.sqrt(np.sum(arr**2, axis=0))
```

(at least for real numbers)

**Comment by Baekalfen** [comment]
I hadn't thought of that. Thanks!
