### ISSUE TITLE
Cannot determine the correct signature (exp:int64)

### ISSUE THREAD

**Issue by Ektorus** [bh107/bohrium#6]
The following code:
```python
import bohrium as bh
bh.exp(bh.arange(10))
```
Gives the following error:
Traceback (most recent call last):
  File "/home/ulrik/BitBucket/masterthesis/bohrium_tests/bohrium_exp.py", line 2, in <module>
    bh.exp(bh.arange(10))
  File "ndarray.pyx", line 74, in ndarray.fix_returned_biclass.inner (/home/ulrik/git/bohrium/build/bridge/npbackend/ndarray.c:1652)
  File "/home/ulrik/.local/lib64/python2.7/site-packages/bohrium/ufunc.py", line 161, in __call__
    (out_dtype, in_dtype) = _util.type_sig(self.info['name'], args)
  File "_util.pyx", line 90, in _util.type_sig (/home/ulrik/git/bohrium/build/bridge/npbackend/_util.c:2211)
TypeError: Cannot determine the correct signature (exp:int64)

**Comment by ZhijieWang** [comment]
Similar issue detected on mac OS X 10.9, Compiled from source
```
➜  markovchain  gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
````

Actual output.


````
Traceback (most recent call last):
  File "markovchaingpu.py", line 2, in <module>
    import bohrium as np
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bohrium/__init__.py", line 11, in <module>
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bohrium/array_create.py", line 7, in <module>
ImportError: cannot import name ndarray
➜  markovchain
```
